import React from 'react';
import { Link } from 'react-router-dom';

const Terms: React.FC = () => (
  <div className="nf-form-container terms-container" style={{ maxWidth: 700, margin: '40px auto', padding: '2em 2.5em', background: '#fff', borderRadius: 12, boxShadow: '0 2px 12px rgba(0,0,0,0.04)', textAlign: 'left', alignItems: 'flex-start', display: 'block', position: 'relative' }}>
    <button className="nf-home-btn" type="button" onClick={() => window.history.back()} aria-label="Close" style={{ position: 'absolute', top: 18, right: 18, fontSize: 22, background: 'none', border: 'none', cursor: 'pointer' }}>&#10005;</button>
    <h2 className="nf-form-title" style={{ marginBottom: 24 }}>Terms of Service</h2>
    <p>Welcome to TypingGenie! By using our website and services, you agree to the following terms. Please read them carefully.</p>

    <h3>1. Service Description</h3>
    <p>TypingGenie is an AI-powered writing assistant that helps users generate, polish, and improve written content such as emails, reports, and documents. The service is provided as-is and may change or be discontinued at any time.</p>

    <h3>2. User Accounts</h3>
    <ul>
      <li>You must provide accurate information when creating an account.</li>
      <li>You are responsible for maintaining the confidentiality of your login credentials.</li>
      <li>Do not share your account or use another person’s account.</li>
    </ul>

    <h3>3. Acceptable Use</h3>
    <ul>
      <li>Do not use TypingGenie for unlawful, harmful, or abusive purposes.</li>
      <li>Do not attempt to reverse engineer, disrupt, or overload the service.</li>
      <li>Generated content is for personal or business use, but you are responsible for its review and appropriate use.</li>
    </ul>

    <h3>4. Privacy</h3>
    <p>We respect your privacy. Please see our <Link to="/privacy">Privacy Policy</Link> for details on how your data is collected, used, and protected.</p>

    <h3>5. AI Content</h3>
    <ul>
      <li>Content generated by TypingGenie is produced by artificial intelligence and may not always be accurate, complete, or appropriate for every situation.</li>
      <li>You are responsible for reviewing and editing all generated content before use.</li>
    </ul>

    <h3>6. Limitation of Liability</h3>
    <ul>
      <li>TypingGenie and its creators are not liable for any damages or losses resulting from your use of the service or reliance on generated content.</li>
      <li>The service is provided without warranties of any kind.</li>
    </ul>

    <h3>7. Changes to Terms</h3>
    <p>We may update these terms from time to time. Continued use of TypingGenie after changes means you accept the new terms.</p>

    <h3>8. Contact</h3>
    <p>If you have questions about these terms, please <Link to="/contact">contact us</Link>.</p>

    <footer className="nf-footer nf-footer-small" style={{ marginTop: 32 }}>
      &copy; {new Date().getFullYear()} TypingGenie. All rights reserved.
    </footer>
  </div>
);

export default Terms;
